export const ADD_SERVER_SUCCESS = 'ADD_SERVER_SUCCESS';
export const ADD_SERVER_FAILURE = 'ADD_SERVER_FAILURE';
export const GET_SERVERS_SUCCESS = 'GET_SERVER_SUCCESS';
export const DELETE_SERVERS_SUCCESS = 'DELETE_SERVERS_SUCCESS';
export const UPDATE_SERVERS_SUCCESS = 'UPDATE_SERVERS_SUCCESS';
